### ISSUE TITLE
Creating our Kanban board

### ISSUE THREAD

**Issue by MarcoDiaz2000** [MarcoDiaz2000/catalog-of-my-things#45]
Link to Kanban board:
https://github.com/MarcoDiaz2000/catalog-of-my-things/projects/1

Our team is integrated by three people and assigned as follows:
@ab-noori will do the tasks of team member # 1
@MarcoDiaz2000 will do the tasks of team member # 2
@tamoorsaeed22 will do the tasks of team member # 3

**Comment by shella12** [comment]
Hi @ab-noori , @MarcoDiaz2000 and @tamoorsaeed22 , 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- All requirements are covered ✔️ 
- Tasks assigned fairly 👍 
- All members have been assigned tasks
- Implemented all requirements 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ab-noori** [comment]
**Hi @shella12 👋,**
Thank you so much 🙏  for reviewing and approving our project.
Your nice feedback is really appreciated 🙏.

![thank-you-gif-22](https://github.com/ab-noori/bookstore-cms/assets/111179533/0848000e-52ce-440c-a114-6c7f859a0eaa)
